# Generated by Django 3.2.4 on 2021-08-31 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('groupid', models.IntegerField(primary_key=True, serialize=False)),
                ('schoolname', models.CharField(max_length=20)),
                ('leadername', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodyTemperature', models.FloatField()),
                ('cough', models.CharField(max_length=2)),
                ('dyspnea', models.CharField(max_length=2)),
                ('soreThroat', models.CharField(max_length=2)),
                ('malaise', models.CharField(max_length=2)),
                ('abnormalTasteAndSmell', models.CharField(max_length=2)),
                ('other', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True, verbose_name='conditionSavedTime')),
                ('name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
