# Generated by Django 3.2.4 on 2021-08-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditions',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='conditionSavedTime'),
        ),
    ]
