# Generated by Django 3.2.4 on 2021-09-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0005_alter_conditions_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditions',
            name='date',
            field=models.DateField(),
        ),
    ]
