# Generated by Django 3.2.4 on 2021-09-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0007_freethrough_threemen'),
    ]

    operations = [
        migrations.AddField(
            model_name='threemen',
            name='accomplish',
            field=models.CharField(default='Yes', max_length=3),
        ),
    ]
