# Generated by Django 3.2.4 on 2021-09-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0008_threemen_accomplish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threemen',
            name='accomplish',
            field=models.CharField(max_length=3),
        ),
    ]
