# Generated by Django 3.2.4 on 2021-09-08 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_userdetail_position'),
        ('club_management', '0009_alter_threemen_accomplish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freethrough',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.userdetail'),
        ),
    ]
