# Generated by Django 3.2.4 on 2021-09-08 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club_management', '0010_alter_freethrough_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freethrough',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
