# Generated by Django 3.2.4 on 2021-09-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0011_alter_freethrough_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('icu_total', models.IntegerField()),
                ('icu_1Q', models.IntegerField()),
                ('icu_2Q', models.IntegerField()),
                ('icu_3Q', models.IntegerField()),
                ('icu_4Q', models.IntegerField()),
                ('op_team', models.CharField(max_length=15)),
                ('op_total', models.IntegerField()),
                ('op_1Q', models.IntegerField()),
                ('op_2Q', models.IntegerField()),
                ('op_3Q', models.IntegerField()),
                ('op_4Q', models.IntegerField()),
            ],
        ),
    ]
