# Generated by Django 3.2.4 on 2021-09-14 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club_management', '0012_matchresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResultDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('underGoalAttempt', models.IntegerField()),
                ('underGoalIn', models.IntegerField()),
                ('middleAttempt', models.IntegerField()),
                ('middleIn', models.IntegerField()),
                ('threePointAttempt', models.IntegerField()),
                ('threePointIn', models.IntegerField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_date', to='club_management.matchresult')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('op_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_team', to='club_management.matchresult')),
            ],
        ),
    ]
