# Generated by Django 3.2.4 on 2021-09-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0013_matchresultdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresultdetail',
            name='faul',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchresultdetail',
            name='turnOver',
            field=models.IntegerField(default=0),
        ),
    ]
