# Generated by Django 3.2.4 on 2021-09-17 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0015_shooting'),
    ]

    operations = [
        migrations.AddField(
            model_name='shooting',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 17, 10, 38, 44, 479745)),
        ),
    ]
